DirectoryStructure/project/homepage/forms.py
# from flask_wtf import Form
# from wtforms import StringField, PasswordField
# from wtforms.validators import DataRequired, Length, EqualTo, Email


# class FormName(Form):
#     FieldName = FieldType(
#         'HTMLName',
#         validators=[DataRequired(), Email(), Length(min=num, max=num), EqualTo('HTMLNameP')])

DirectoryStructure/project/admin/views.py
# _*_ coding: utf-8 _*_
from functools import wraps
from flask import flash, redirect, render_template, \
   request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError 


from .forms import AdminLoginForm
from project import db
from project.models import User, Post, Comment

#helper functions 
# def blog_post_finder(postTitle):
#     postTitle = u'{}'.format(postTitle)
#     return db.session.query(Post).filter_by(title=postTitle).first()

# def page_number():
#     blog_posts_numbers = db.session.query(Post).count()
#     pageNumber = blog_posts_numbers / 5 
#     if blog_posts_numbers % 5 > 0 :
#         pageNumber += 1 
#     return pageNumber

# def posts(pageNumber):
#     start = ((pageNumber-1)*5) + 1
#     end = (pageNumber*5) + 1
#     return db.session.query(Post).order_by(Post.date.asc())[start:end]

# def comment_search(searchID):
#     return db.session.query(Comment).order_by(Comment.date.asc()).filter_by(Post_ID=searchID)

#This bluePrint includes user registration and users profile system 
admin_blueprint = Blueprint('admin', __name__)


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


@admin_blueprint.route('/admin', methods=['GET', 'POST'])
def admin_redirect():
    error = None
    form = AdminLoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            # user = User.query.filter_by(tele_number=request.form['telegram_number']).filter_by(payment_verify=1).first()
            username = "admin"
            password = "test"
            if username is not None and str(username) == str(request.form['username']) and str(password) == str(request.form['password']):
                session['logged_in'] = True
                return redirect(url_for('homepage.main'))
            else:
                "user credentials"
        else:
            print "not validate"
    else:
        print "request.method"

    return render_template('administrator.html', form=form, error=error)


# @admin_blueprint.route('/ad')
# @blog_blueprint.route('/blog/page/<int:pageNumber>')
# def blog(pageNumber):
#     currentPage = pageNumber
#     pages = page_number()
#     if currentPage <= pages:
#         posts_for_specific_page = posts(currentPage)
#     return render_template('blog.html', numbers=pages, posts=posts_for_specific_page)



# @blog_blueprint.route('/blog/post/<postTitle>')
# def blog_post(postTitle):
#     post = postTitle.split("-")
#     postTitle = " ".join(post)
#     post = blog_post_finder(postTitle)
#     comment_id_to_search = post.post_id
#     comments = comment_search(comment_id_to_search)
#     for i in comments:
#         print i.comment
#     return render_template('post2.html', post=post, comments=comments)

DirectoryStructure/project/blog/views.py
# _*_ coding: utf-8 _*_
from functools import wraps
from flask import flash, redirect, render_template, \
   request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError 


# from .forms import LoginForm
from project import db
from project.models import User, Post, Comment

#helper functions 
def blog_post_finder(postTitle):
    postTitle = u'{}'.format(postTitle)
    return db.session.query(Post).filter_by(title=postTitle).first()

def page_number():
    blog_posts_numbers = db.session.query(Post).count()
    pageNumber = blog_posts_numbers / 5 
    if blog_posts_numbers % 5 > 0 :
        pageNumber += 1 
    return pageNumber

def posts(pageNumber):
    start = ((pageNumber-1)*5) + 1
    end = (pageNumber*5) + 1
    return db.session.query(Post).order_by(Post.date.asc())[start:end]

def comment_search(searchID):
    return db.session.query(Comment).order_by(Comment.date.asc()).filter_by(Post_ID=searchID)

#This bluePrint includes user registration and users profile system 
blog_blueprint = Blueprint('blog', __name__)


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


@blog_blueprint.route('/blog')
def blog_redirect():
    return redirect(url_for('blog', pageNumber=1))

@blog_blueprint.route('/blog/page/<int:pageNumber>')
def blog(pageNumber):
    currentPage = pageNumber
    pages = page_number()
    if currentPage <= pages:
        posts_for_specific_page = posts(currentPage)
    return render_template('blog.html', numbers=pages, posts=posts_for_specific_page)



@blog_blueprint.route('/blog/post/<postTitle>')
def blog_post(postTitle):
    post = postTitle.split("-")
    postTitle = " ".join(post)
    post = blog_post_finder(postTitle)
    comment_id_to_search = post.post_id
    comments = comment_search(comment_id_to_search)
    for i in comments:
        print i.comment
    return render_template('post2.html', post=post, comments=comments)

DirectoryStructure/project/homepage/views.py
from functools import wraps
from flask import flash, redirect, render_template, \
   request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError 


# from .forms import $$
from project import db
from project.models import User




homepage_blueprint = Blueprint('homepage', __name__)


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap



@homepage_blueprint.route('/')
@homepage_blueprint.route('/main')
def main():
	return render_template("homepage.html"), 200

DirectoryStructure/project/templates/22.html
<!DOCTYPE html>
<html class="no-js" lang="en" dir="rtl">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    {% endblock %}
  </head>
  <body>
  <div class="off-canvas-wrapper">
     
    <!-- MOBILE NAVIGATION -->
    
     <div class="off-canvas position-right" id="offCanvas" data-off-canvas data-transition="overlap">
      <ul class="MobileMenu">
        <li><a href="#">خانه</a></li>
        <li><a href="#">ورود</a></li>
        <li><a href="#">ثبت نام</a></li>
        <li><a href="#">بلاگ</a></li>
      </ul>
     </div>
  


    <div class="off-canvas-content" data-off-canvas-content>
        <div class="title-bar show-for-small-only">
            <div class="title-bar-right">
            <button class="menu-icon" type="button" data-open="offCanvas"></button>
            <span class="title-bar-title">فرنچ آنلاین</span>
            </div>
        </div>
      <!-- Your page content lives here -->

<!-- DESKTOP NVAIGATION FOR LOGGED-IN USERS -->
  {% if 'logged_in' in session %}
        <div data-sticky-container>
      <nav class="top-bar nav-desktop" data-sticky data-options="marginTop:0;">
        <div class="wrap">

          <div class="top-bar-right">
              <h4 class="menu-text">فرنچ آنلاین</h4>
          </div>

          <div class="top-bar-left">
            <ul class="menu menu-desktop">
              <li><a href="{{ url_for('homepage.main') }}">خانه</a></li>
              <li><a href="{{ url_for('profiles.profile') }}">حساب کاربری</a></li>
              <li><a href="{{ url_for('profiles.logout') }}">خروج</a></li>
              <li><a href="{{ url_for('blog.blog', pageNumber=1) }}">بلاگ</a></li>
              <li><a href="{{ url_for('songs.song') }}">موریک</a></li>
            </ul>
          </div>

        </div>
       </nav>
    </div>

    {% else %}
        <!-- NAVIGATION DESKTOP -->
    <div data-sticky-container>
      <nav class="top-bar nav-desktop" data-sticky data-options="marginTop:0;">
        <div class="wrap">

          <div class="top-bar-right">
              <h4 class="menu-text">فرنچ آنلاین</h4>
          </div>

          <div class="top-bar-left">
            <ul class="menu menu-desktop">
              <li><a href="{{ url_for('homepage.main') }}">خانه</a></li>
              <li><a href="{{ url_for('profiles.login') }}">ورود</a></li>
              <li><a href="{{ url_for('registeration.register') }}">ثبت نام</a></li>
              <li><a href="{{ url_for('blog.blog', pageNumber=1) }}">بلاگ</a></li>
              <li><a href="{{ url_for('songs.song') }}">موریک</a></li>
            </ul>
          </div>

        </div>

      </nav>
    </div>

    {% endif %}
      {% block content %}
      {% endblock %}

 
    <footer>
      <div class="wrap row small-up-1 medium-up-3">
        <div class="column">
          <h4>اطلاعات تماس</h4>
          <hr>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
        </div>

        <div class="column">
          <h4>نقشه سایت</h4>
          <hr>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
        </div>

        <div class="column">
          <h4>شبکه های اجتماعی</h4>
          <hr>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
        </div>

      </div>
    </footer>

  </div>
</div>
    <script src="{{ url_for('static', filename='js/vendor/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/what-input.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
  </body>
</html>

DirectoryStructure/project/templates/_base.html
<!DOCTYPE html>
<html class="no-js" lang="en" dir="rtl">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    {% endblock %}
  </head>
  <body>
  <div class="off-canvas-wrapper">
     
    <!-- MOBILE NAVIGATION -->
    
     <div class="off-canvas position-right" id="offCanvas" data-off-canvas data-transition="overlap">
      <ul class="MobileMenu">
        <li><a href="#">خانه</a></li>
        <li><a href="#">ورود</a></li>
        <li><a href="#">ثبت نام</a></li>
        <li><a href="#">بلاگ</a></li>
      </ul>
     </div>
  


    <div class="off-canvas-content" data-off-canvas-content>
        <div class="title-bar show-for-small-only">
            <div class="title-bar-right">
            <button class="menu-icon" type="button" data-open="offCanvas"></button>
            <span class="title-bar-title">فرنچ آنلاین</span>
            </div>
        </div>
      <!-- Your page content lives here -->

<!-- DESKTOP NVAIGATION FOR LOGGED-IN USERS -->
  {% if 'logged_in' in session %}
        <div data-sticky-container>
      <nav class="top-bar nav-desktop" data-sticky data-options="marginTop:0;">
        <div class="wrap">

          <div class="top-bar-right">
              <h4 class="menu-text">فرنچ آنلاین</h4>
          </div>

          <div class="top-bar-left">
            <ul class="menu menu-desktop">
              <li><a href="{{ url_for('homepage.main') }}">خانه</a></li>
              <li><a href="{{ url_for('profiles.profile') }}">حساب کاربری</a></li>
              <li><a href="{{ url_for('profiles.logout') }}">خروج</a></li>
              <li><a href="{{ url_for('blog.blog', pageNumber=1) }}">بلاگ</a></li>
              <li><a href="{{ url_for('songs.song') }}">موریک</a></li>
            </ul>
          </div>

        </div>
       </nav>
    </div>

    {% else %}
        <!-- NAVIGATION DESKTOP -->
    <div data-sticky-container>
      <nav class="top-bar nav-desktop" data-sticky data-options="marginTop:0;">
        <div class="wrap">

          <div class="top-bar-right">
              <h4 class="menu-text">فرنچ آنلاین</h4>
          </div>

          <div class="top-bar-left">
            <ul class="menu menu-desktop">
              <li><a href="{{ url_for('homepage.main') }}">خانه</a></li>
              <li><a href="{{ url_for('profiles.login') }}">ورود</a></li>
              <li><a href="{{ url_for('registeration.register') }}">ثبت نام</a></li>
              <li><a href="{{ url_for('blog.blog', pageNumber=1) }}">بلاگ</a></li>
              <li><a href="{{ url_for('songs.song') }}">موریک</a></li>
            </ul>
          </div>

        </div>

      </nav>
    </div>

    {% endif %}
      {% block content %}
      {% endblock %}

 
    <footer>
      <div class="wrap row small-up-1 medium-up-3">
        <div class="column">
          <h4>اطلاعات تماس</h4>
          <hr>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
        </div>

        <div class="column">
          <h4>نقشه سایت</h4>
          <hr>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
        </div>

        <div class="column">
          <h4>شبکه های اجتماعی</h4>
          <hr>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
          <a href="#"><span>Phone</span> +98 935 904 5545</a>
        </div>

      </div>
    </footer>

  </div>
</div>
    <script src="{{ url_for('static', filename='js/vendor/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/what-input.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
  </body>
</html>

DirectoryStructure/project/templates/administrator.html
{% extends "_base.html" %}
{% block title %}blog FREnchOnline{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
{% endblock %}
{% block content %}
<div class="wrap">
	<form action="{{ url_for('admin.admin_redirect')}}" method="POST">
		      {{ form.csrf_token }}
	<p>نام کاربری</p>	{{form.username}}

	<p>pass</p> {{ form.password}}
	  <input type="submit" value="Submit">
	</form>
</div>
{% endblock %}

DirectoryStructure/project/templates/blog.html
{% extends "_base.html" %}
{% block title %}blog FREnchOnline{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
{% endblock %}
{% block content %}
    <div class="callout large primary">
      <div class="row column text-center">
        <h1>Our Blog</h1>
      </div>
    </div>
    
    <div class="row" id="content">
      <div class="medium-8 columns">
        {% for post in posts %}
        <div class="blog-post">
          <h3>{{ post.title }}<small>{{ post.date }}</small></h3>
          <img class="thumbnail" src="../static/img/{{ post.cover_path }}">
          <p>{{ post.body }}</p>
          <div class="callout">
            <ul class="menu simple subpost">
              <li><a href="#">نویسنده: {{ post.author }}</a></li>
              <li><a href="#">نظرات: 3</a></li>
              <li><a href="">تعداد بازدیدها: {{ post.views }}</a></li>
            </ul>
          </div>
        </div>
        <hr />
        {% endfor %}

      </div>
      <div class="medium-3 columns" data-sticky-container>
        <div class="sticky" data-sticky data-anchor="content">
          <h4>Categories</h4>
          <ul>
            <li><a href="#">Skyler</a></li>
            <li><a href="#">Jesse</a></li>
            <li><a href="#">Mike</a></li>
            <li><a href="#">Holly</a></li>
          </ul>

          <h4>Authors</h4>
          <ul>
            <li><a href="#">Skyler</a></li>
            <li><a href="#">Jesse</a></li>
            <li><a href="#">Mike</a></li>
            <li><a href="#">Holly</a></li>
          </ul>
        </div>
      </div>
    </div>
    
    <div class="row column">
      <ul class="pagination" role="navigation" aria-label="Pagination">
        <li class="disabled">Previous</li>
        {% for number in range(0, numbers)%}
        <li><a href="http://127.0.0.1:5000/blog/page/{{ number+1 }}" aria-label="Page {{ number+1 }}">{{ number+1 }}</a></li>
        {% endfor %}
<!--         <li class="current"><span class="show-for-sr">You're on page</span> 1</li>
        <li><a href="#" aria-label="Page 2">2</a></li>
        <li><a href="#" aria-label="Page 3">3</a></li>
        <li><a href="#" aria-label="Page 4">4</a></li>
        <li class="ellipsis"></li>
        <li><a href="#" aria-label="Page 12">12</a></li>
        <li><a href="#" aria-label="Page 13">13</a></li> -->
        <li><a href="#" aria-label="Next page">Next</a></li>
      </ul>
    </div>
    
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>
{% endblock %}

DirectoryStructure/project/templates/login.html
<form action="{{ url_for('profiles.login')}}" method="POST">
	      {{ form.csrf_token }}
<p>num</p>	{{form.telegram_number}}

<p>pass</p> {{ form.password}}
  <input type="submit" value="Submit">
</form>

DirectoryStructure/project/templates/post.html
{% extends "_base.html" %}
{% block title %}blog FREnchOnline{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
{% endblock %}
{% block content %}
{{ post.title }}
{{ post.body }}
{% endblock %}

DirectoryStructure/project/templates/post2.html
{% extends "_base.html" %}
{% block title %}blog FREnchOnline{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
{% endblock %}
{% block content %}
    <!-- End Top Bar -->

    <div class="callout large primary">
      <div class="row column text-center">
        <h1>{{ post.title }}</h1>
        <h2 class="subheader">{{ post.subtitle }}</h2>
      </div>
    </div>
    <!-- We can now combine rows and columns when there's only one column in that row -->
    <div class="row medium-8 large-8 columns">
      <div class="blog-post">
        <h3><small>{{ post.date }}</small></h3>
        <img class="thumbnail" src="http://placehold.it/850x350">
        <p>{{ post.body }}</p>
        <div class="callout">
          <ul class="menu simple subpost">
            <li><a href="#">نویسنده: {{ post.author }}</a></li>
            <li><a href="#">Comments: 3</a></li>
            <li><a href="#">تعداد بازدید: {{ post.views }}</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="comment_section row medium-8 large-8 columns">
      {% for comment in comments %}
      {{ comment.name }}
      {{ comment.date }}
      {{ comment.comment }}
      {% endfor %}
    </div>
{% endblock %}

    

DirectoryStructure/project/templates/profile.html
{% extends "_base.html" %}
{% block title %}profile{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
{% endblock %}
{% block content %}
    <div class="callout large primary">
      <div class="row column text-center">
        <h1>Our Blog</h1>
      </div>
    </div>
    
    <div class="row" id="content">
      <center>
        <div class="medium-2 columns" data-sticky-container>
          <div class="sticky" data-sticky data-anchor="content">
            <h4>پروفایل</h4>
            <h6>{{ session["name"] }}</h6>
            <ul>
              <li><a href="#">مشاهده دروس</a></li>
              <li><a href="#">پرسش سوال</a></li>
              <li><a href="#"></a></li>
              <li><a href="#">Holly</a></li>
            </ul>
          </div>
        </div>
      </center>

      <div class="medium-9 columns">
        <div class="blog-post">
          <h3>Awesome blog post title <small>3/6/2015</small></h3>
          <img class="thumbnail" src="http://placehold.it/850x350">
          <p>Praesent id metus massa, ut blandit odio. Proin quis tortor orci. Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus condimentum laoreet. Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus.</p>
          <div class="callout">
            <ul class="menu simple">
              <li><a href="#">Author: Mike Mikers</a></li>
              <li><a href="#">Comments: 3</a></li>
            </ul>
          </div>
        </div>

        <div class="blog-post">
          <h3>Awesome blog post title <small>3/6/2015</small></h3>
          <img class="thumbnail" src="http://placehold.it/850x350">
          <p>Praesent id metus massa, ut blandit odio. Proin quis tortor orci. Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus condimentum laoreet. Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus.</p>
          <div class="callout">
            <ul class="menu simple">
              <li><a href="#">Author: Mike Mikers</a></li>
              <li><a href="#">Comments: 3</a></li>
            </ul>
          </div>
        </div>

        <div class="blog-post">
          <h3>Awesome blog post title <small>3/6/2015</small></h3>
          <img class="thumbnail" src="http://placehold.it/850x350">
          <p>Praesent id metus massa, ut blandit odio. Proin quis tortor orci. Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus condimentum laoreet. Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus.</p>
          <div class="callout">
            <ul class="menu simple">
              <li><a href="#">Author: Mike Mikers</a></li>
              <li><a href="#">Comments: 3</a></li>
            </ul>
          </div>
        </div>

        <div class="blog-post">
          <h3>Awesome blog post title <small>3/6/2015</small></h3>
          <img class="thumbnail" src="http://placehold.it/850x350">
          <p>Praesent id metus massa, ut blandit odio. Proin quis tortor orci. Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus condimentum laoreet. Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus.</p>
          <div class="callout">
            <ul class="menu simple">
              <li><a href="#">Author: Mike Mikers</a></li>
              <li><a href="#">Comments: 3</a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
    
    <div class="row column">
      <ul class="pagination" role="navigation" aria-label="Pagination">
        <li class="disabled">Previous</li>
        <li class="current"><span class="show-for-sr">You're on page</span> 1</li>
        <li><a href="#" aria-label="Page 2">2</a></li>
        <li><a href="#" aria-label="Page 3">3</a></li>
        <li><a href="#" aria-label="Page 4">4</a></li>
        <li class="ellipsis"></li>
        <li><a href="#" aria-label="Page 12">12</a></li>
        <li><a href="#" aria-label="Page 13">13</a></li>
        <li><a href="#" aria-label="Next page">Next</a></li>
      </ul>
    </div>
{% endblock %}

DirectoryStructure/project/templates/recaptcha.html
<!--#{{ form.recaptcha() }}
                           #   {% if form.recaptcha.errors %}
				<span class="error">
				#{% for error in form.recaptcha.errors %} -->


				<script>
				swal("caution", "لطفا 'من ربات نیستم' را تیک بزیند.", 'error')
				</script>
				{% endfor %}

					</span>
				{% endif %}

DirectoryStructure/project/templates/testUp.html
{% extends "_base.html" %}
{% block title %}blog FREnchOnline{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
{% endblock %}
{% block content %}
<div class="wrap">
      <form action="upload" method="post" enctype="multipart/form-data">
        <input type="file" name="file"><br /><br />
        <input type="submit" value="Upload">
      </form>
</div>
{% endblock %}